basePath: /api
definitions:
  api.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  api.SuccessResponse:
    properties:
      success:
        type: boolean
    type: object
  api.UserIdResponse:
    properties:
      id:
        type: string
    type: object
  api.UserRequest:
    properties:
      admin:
        type: boolean
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  api.UserResponse:
    properties:
      admin:
        type: boolean
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:8888
info:
  contact: {}
  description: This is API for service Users.
  title: Swagger Users API
  version: "1.0"
paths:
  /v1/users:
    get:
      description: Get a list of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.UserResponse'
            type: array
      security:
      - BasicAuth: []
      summary: Get Users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided information (requires admin
        access)
      parameters:
      - description: User object to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BasicAuth: []
      summary: Create User
      tags:
      - Users
  /v1/users/{id}:
    delete:
      description: Delete a user by ID (requires admin access)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: User deleted successfully
          schema:
            $ref: '#/definitions/api.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BasicAuth: []
      summary: Delete User
      tags:
      - Users
    get:
      description: Get information about a specific user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BasicAuth: []
      summary: Get User Information
      tags:
      - Users
    put:
      description: Update a user with the provided information (requires admin access)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User object to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/api.UserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BasicAuth: []
      summary: Update User
      tags:
      - Users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
